/* tslint:disable */
/* eslint-disable */
/**
 * QuizApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GeneralDto
 */
export interface GeneralDto {
    /**
     * 
     * @type {boolean}
     * @memberof GeneralDto
     */
    isSuccessful?: any;
    /**
     * 
     * @type {string}
     * @memberof GeneralDto
     */
    reason?: any | null;
}
