/* tslint:disable */
/* eslint-disable */
/**
 * QuizApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GetUserResponse
 */
export interface GetUserResponse {
    /**
     * 
     * @type {string}
     * @memberof GetUserResponse
     */
    username: any;
    /**
     * 
     * @type {string}
     * @memberof GetUserResponse
     */
    email: any;
    /**
     * 
     * @type {string}
     * @memberof GetUserResponse
     */
    avatar?: any | null;
    /**
     * 
     * @type {string}
     * @memberof GetUserResponse
     */
    id?: any;
    /**
     * 
     * @type {Array&lt;FriendModel&gt;}
     * @memberof GetUserResponse
     */
    friends?: any | null;
}
