/* tslint:disable */
/* eslint-disable */
/**
 * QuizApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PostUserResponse
 */
export interface PostUserResponse {
    /**
     * 
     * @type {string}
     * @memberof PostUserResponse
     */
    username: any;
    /**
     * 
     * @type {string}
     * @memberof PostUserResponse
     */
    email: any;
    /**
     * 
     * @type {string}
     * @memberof PostUserResponse
     */
    avatar?: any | null;
}
