/* tslint:disable */
/* eslint-disable */
/**
 * QuizApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PostGameResponse
 */
export interface PostGameResponse {
    /**
     * 
     * @type {string}
     * @memberof PostGameResponse
     */
    id?: any;
    /**
     * 
     * @type {BaseUserModel}
     * @memberof PostGameResponse
     */
    user1?: any;
    /**
     * 
     * @type {BaseUserModel}
     * @memberof PostGameResponse
     */
    user2?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PostGameResponse
     */
    isDone?: any;
}
